require:
  - rubocop-md
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7.0
  NewCops: enable
  Exclude:
    - .git/**/*
    - vendor/bundle/**/*

Layout/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/MethodLength:
  Max: 12
  Exclude:
    - lib/package/audit/cli.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false