module Package
  module Audit
    module Formatter
      class VersionDate
        SECONDS_PER_YEAR: Integer

        @date: String

        def initialize: (String) -> void

        def format: -> void
      end
    end
  end
end
