module Package
  module Audit
    module Formatter
      class Version
        @curr: String
        @target: String

        def initialize: (String, String) -> void

        def format: -> String
      end
    end
  end
end
