module Package
  module Audit
    module Util
      module SummaryPrinter
        def self.deprecated: -> void

        def self.report: -> void

        def self.risk: -> void

        def self.statistics: (String, Array[Package]) -> void

        def self.total: (String, Array[Package]) -> void

        def self.vulnerable: (String, String) -> void
      end
    end
  end
end
