module Package
  module Audit
    module Util
      module SummaryPrinter
        def self.all: -> void

        def self.deprecated: -> void

        def self.risk: -> void

        def self.statistics: (String, Symbol, Array[Package], Array[Package]) -> void

        def self.total: (String, Symbol, Array[Package], Array[Package]) -> void

        def self.vulnerable: (String, String?) -> void
      end
    end
  end
end
