module Package
  module Audit
    module Util
      module SummaryPrinter
        def self.all: -> void

        def self.count_status: (Array[Package], Symbol) -> Integer

        def self.deprecated: -> void

        def self.display_results: (String, Symbol, Array[Package], Array[Package], Hash[Symbol, Integer]) -> void

        def self.statistics: (String, Symbol, Array[Package], Array[Package]) -> void

        def self.status_message: (Hash[Symbol, Integer]) -> String

        def self.total: (String, Symbol, Array[Package], Array[Package]) -> void

        def self.vulnerable: (String, String?) -> void

        def self.deprecated_details: (Hash[Symbol, Integer]) -> String

        def self.outdated_details: (Hash[Symbol, Integer]) -> String

        def self.vulnerability_details: (Hash[Symbol, Integer]) -> String

        def calculate_statistics: (Array[Package], Array[Package]) -> Hash[Symbol, Integer]
      end
    end
  end
end
