module Package
  module Audit
    class Risk
      attr_reader explanation: String?
      attr_reader type: String

      def initialize: (String, ?String?) -> void

      def <=>: (Risk) -> Integer?
    end
  end
end
