module Const
  BUNDLE_AUDIT_CMD: String
  BUNDLE_AUDIT_CMD_JSON: String
  DEFAULT_FIELDS: Array[Symbol]
  FIELDS: Array[Symbol]
  HEADERS: Hash[Symbol, String]
  SECONDS_ELAPSED_TO_BE_OUTDATED: Integer
  YARN_AUDIT_CMD: String
  YARN_AUDIT_CMD_JSON: String
  YEARS_ELAPSED_TO_BE_OUTDATED: Integer
  SECONDS_PER_YEAR: Integer
end
