module Package
  module Audit
    module Enum
      module Environment
        DEFAULT: Symbol
        DEV: Symbol
        PRODUCTION: Symbol
        STAGING: Symbol
        TEST: Symbol
      end
    end
  end
end
