module Package
  module Audit
    module Enum
      module Environment
        DEFAULT: String
        DEV: String
        PRODUCTION: String
        STAGING: String
        TEST: String

        def self.all: -> Array[String]
      end
    end
  end
end
