module Package
  module Audit
    module Enum
      module Option
        CONFIG: String
        CSV: String
        CSV_EXCLUDE_HEADERS: String
        ENVIRONMENT: String
        INCLUDE_IGNORED: String
        TECHNOLOGY: String
      end
    end
  end
end
