module Package
  module Audit
    module Enum
      module Option
        CONFIG: String
        FORMAT: String
        EXCLUDE_HEADERS: String
        GROUP: String
        INCLUDE_IGNORED: String
        TECHNOLOGY: String
      end
    end
  end
end
