module Package
  module Audit
    module Enum
      module RiskExplanation
        OUTDATED: String
        OUTDATED_BY_MAJOR_VERSION: String
        POTENTIAL_DEPRECATION: String
        VULNERABILITY: String
      end
    end
  end
end