source 'https://rubygems.org'

gem 'irb', '1.7.0'
gem 'rack', '2.2.0.0'

group :development do
  gem 'reline', '0.3.0'
  gem 'yard', '0.9.26'
end

group :test do
  gem 'minitest', '5.10.0'
end

group :production do
  gem 'tzinfo', '1.2.1'
end
