module Package
  module Audit
    class CommandService
      NODE_MODULE: String
      RUBY_GEM: String

      @dir: String
      @options: Hash[Symbol, untyped]

      def initialize: (String, Hash[Symbol, untyped]) -> void

      def all: -> bool

      def deprecated: -> bool

      def outdated: -> bool

      def vulnerable: -> bool

      private

      def node?: -> bool?

      def print_success_message: (String) -> void

      def ruby?: -> bool?
    end
  end
end
