module Package
  module Audit
    class Package
      @groups: Array[Symbol]
      @risk: Risk
      @vulnerabilities: Array[String]

      attr_accessor groups: Array[Symbol]
      attr_accessor latest_version: String
      attr_accessor latest_version_date: String
      attr_reader name: String
      attr_reader version: String
      attr_accessor version_date: String
      attr_accessor vulnerabilities: Array[String]

      def initialize: (String, String) -> void

      def full_name: -> String

      def group_list: -> String

      def risk?: -> bool

      def risk: -> Risk

      def risk_explanation: -> String?

      def risk_type: -> String

      def to_csv: (Array[Symbol]) -> String

      def update: (**untyped) -> void

      def vulnerabilities_grouped: -> String
    end
  end
end
