module Package
  module Audit
    class RiskCalculator
      @pkg: Package

      def initialize: (Package) -> void

      def find: -> Risk?

      private

      def assess_deprecation_risk: -> Risk

      def assess_version_risk: -> Risk

      def assess_vulnerability_risk: -> Risk

      def production_dependency?: -> bool
    end
  end
end
