module Package
  module Audit
    class RiskCalculator
      @dependency: Dependency

      def initialize: (Dependency) -> void

      def find: -> Risk?

      private

      def assess_version_risk: -> Risk

      def assess_vulnerability_risk: -> Risk
    end
  end
end
