module Package
  module Audit
    module Ruby
      class BundlerSpecs
        def self.all: (String) -> Array[Dependency]

        def self.gemfile: (String) -> Array[Dependency]

        def self.gems_from_specs: (Array[untyped]) -> Array[Dependency]

        def self.vulnerable: (String) -> Array[Dependency]
      end
    end
  end
end
