module Package
  module Audit
    module Ruby
      class GemCollection
        @dir: String

        def self.all: -> Array[Package]

        def self.deprecated: -> Array[Package]

        def self.outdated: (?include_implicit: bool) -> Array[Package]

        def self.vulnerable: -> Array[Package]
      end
    end
  end
end
