module Package
  module Audit
    module Ruby
      class GemMetaData
        @dependencies: Array[Package]

        @gem_hash: Hash[String, Package]

        def initialize: (Array[Package]) -> void

        def fetch: -> Array[Package]

        def find: -> Array[Package]

        private

        def assign_groups: -> Array[Package]

        def find_rubygems_metadata: -> Array[Package]
      end
    end
  end
end
