module Package
  module Audit
    module Ruby
      class GemCollection
        @dir: String

        def initialize: (String) -> void

        def all: -> Array[Package]

        def deprecated: -> Array[Package]

        def outdated: (?include_implicit: bool) -> Array[Package]

        def vulnerable: -> Array[Package]
      end
    end
  end
end
