module Package
  module Audit
    module Ruby
      class GemMetaData
        @dependencies: Array[Dependency]

        def initialize: (Array[Dependency]) -> void

        def find: -> Array[Dependency]
      end
    end
  end
end
