module Package
  module Audit
    module Const
      module Cmd
        BUNDLE_AUDIT: String
        BUNDLE_AUDIT_JSON: String
        NPM_AUDIT: String
        NPM_AUDIT_JSON: String
        YARN_AUDIT: String
        YARN_AUDIT_JSON: String
      end
    end
  end
end
