module Package
  module Audit
    module Const
      module Fields
        ALL: Array[Symbol]
        AVAILABLE: Array[Symbol]
        DEPRECATED: Array[Symbol]
        HEADERS: Hash[Symbol, String]
        OUTDATED: Array[Symbol]
        VULNERABLE: Array[Symbol]
      end
    end
  end
end
