module Package
  module Audit
    module Const
      module Time
        SECONDS_ELAPSED_TO_BE_OUTDATED: Integer
        SECONDS_PER_YEAR: Integer
        YEARS_ELAPSED_TO_BE_OUTDATED: Integer
      end
    end
  end
end
