module Package
  module Audit
    module Npm
      class NodeCollection
        @dir: String
        @report: Symbol

        def initialize: (String, Symbol) -> void

        def all: -> Array[Package]

        def deprecated: -> Array[Package]

        def fetch: -> Array[Package]

        def outdated: -> Array[Package]

        def vulnerable: -> Array[Package]

        private

        def fetch_from_lock_file: -> Array[Package]

        def fetch_from_package_json: -> Array[Hash[Symbol, untyped]]
      end
    end
  end
end
