module Package
  module Audit
    class CommandParser
      @config: Hash[String, untyped]?
      @dir: String
      @groups: Array[String]
      @spinner: Util::Spinner
      @options: Hash[String, untyped]
      @report: Symbol
      @technologies: Array[String]

      def initialize: (String, Hash[String, untyped], Symbol) -> void

      def run: -> int

      private

      def human_readable_technologies: -> String

      def learn_more_command: (String) -> String?

      def parse_config_file!: -> Hash[String, untyped]?

      def parse_technologies: -> Array[String]

      def parse_technologies!: -> Array[String]

      def print_disclaimer: (String) -> void

      def print_results: (String, Array[Package], Array[Package]) -> void

      def print_summary: (String, Array[Package], Array[Package]) -> void

      def process_technologies: -> int

      def validate_format!: -> void
    end
  end
end
