module Package
  module Audit
    class PackagePrinter
      BASH_FORMATTING_REGEX: Regexp
      COLUMN_GAP: Integer
      CSV_HEADERS: Hash[Symbol, String]

      @pkgs: Array[Package]
      @options: Hash[String, untyped]

      def initialize: (Hash[String, untyped], Array[Package]) -> void

      def print: (Array[Symbol]) -> void

      private

      def check_fields: (Array[Symbol]) -> void

      def csv: (Array[Symbol], ?exclude_headers: bool) -> void

      def pretty: (?Array[Symbol]) -> void
    end
  end
end
