module Package
  module Audit
    class PackageFilter
      @config: Hash[String, untyped]?
      @report: Symbol

      def initialize: (Symbol, Hash[String, untyped]?) -> void

      def ignored?: (Package) -> bool

      private

      def ignore_deprecated?: (Package, Hash[String, untyped]?) -> bool

      def ignore_outdated?: (Package, Hash[String, untyped]?) -> bool

      def ignore_package?: (Package, Hash[String, untyped]?) -> bool

      def ignore_vulnerable?: (Package, Hash[String, untyped]?) -> bool

      def pkg_version_in_config?: (Package, Hash[String, untyped]?) -> bool

      def pkg_yaml_from_config: (Package) -> Hash[String, untyped]?
    end
  end
end
