name: Test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [ '3.2', '3.1', '3.0', '2.7', '2.6' ]

    steps:
      - uses: actions/checkout@v3
      - name: Delete Gemfile.lock
        run: rm Gemfile.lock
      - name: Update RubyGems
        run: gem update --system
      - name: Install latest bundler
        run: gem install bundler
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test